name: CI
on: [push, pull_request]

env:
  BUILD_PROFILE: Release

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: msbuild /p:Configuration=${{ env.BUILD_PROFILE }}
      - name: Extract Short Commit Hash
        id: extract
        shell: bash
        run: echo ::set-output name=commit::`git rev-parse --short HEAD`
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: RePak-${{ steps.extract.outputs.commit }}
          path: |
            bin/${{ env.BUILD_PROFILE }}/*.dll
            bin/${{ env.BUILD_PROFILE }}/*.exe
            bin/${{ env.BUILD_PROFILE }}/*.pdb
            bin/${{ env.BUILD_PROFILE }}/*.txt
