name: CI
on: [push, pull_request]

env:
  BUILD_PROFILE: Release

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: msbuild /p:Configuration=${{ env.BUILD_PROFILE }}
      - name: Extract Short Commit Hash
        id: extract
        shell: bash
        run: echo commit=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RePak-${{ steps.extract.outputs.commit }}
          path: |
            bin/*.dll
            bin/*.exe
            bin/*.pdb
            bin/*.txt
